In [1]:
import pandas as pd

data = pd.read_csv('../dataset/raw_data/Country Wise Yearly VIsitors.csv')

# convert wide → long
data_long = data.melt(id_vars=['Country'], 
                      var_name='Year', 
                      value_name='Visitors')

data_long['Year'] = data_long['Year'].astype(int)

data_long.head()

     Country  Year  Visitors
0     Canada  2014    268485
1      U.S.A  2014   1118983
2  Argentina  2014      9731
3     Brazil  2014     19563
4     Mexico  2014     13978

In [5]:
import pandas as pd

# load raw data
data = pd.read_csv('../dataset/raw_data/Country Wise Yearly VIsitors.csv')

# convert wide → long
data_long = data.melt(id_vars=['Country'], 
                      var_name='Year', 
                      value_name='Visitors')

# fix datatype
data_long['Year'] = data_long['Year'].astype(int)

# SAVE processed data here 👇
data_long.to_csv('../dataset/processed_data/cleaned_data.csv', index=False)

data_long.head()

     Country  Year  Visitors
0     Canada  2014    268485
1      U.S.A  2014   1118983
2  Argentina  2014      9731
3     Brazil  2014     19563
4     Mexico  2014     13978